#Randomly choose absorption layer POI and calculate the scattering angle

import numpy as np
import random
import math
import matplotlib.pyplot as plt
# import sympy as sym
import pandas as pd 
import os
import time
from pathlib import Path

# import system_matrix.code.config as config
from . import params


REPO_ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = REPO_ROOT / "data" / "idealData_100"


size_sourcePlane = 1
size_scatterPlane = 2
size_absorbPlane = 6

#3 variables define the current source position for one image/csv
Current_source_x = 20
Current_source_y = 25
Current_source_z = -123

def genSimEvents(noOfSources, noOfEvents) :

    scatterPlane_indices_x = np.zeros((noOfSources, noOfEvents))
    scatterPlane_indices_y = np.zeros((noOfSources, noOfEvents))
    scatterPlane_indices_z = np.zeros((noOfSources, noOfEvents))

    absorbPlane_indices_x = np.zeros((noOfSources, noOfEvents))
    absorbPlane_indices_y = np.zeros((noOfSources, noOfEvents))
    absorbPlane_indices_z = np.zeros((noOfSources, noOfEvents))


    sourcePlane_indices_x = np.zeros(noOfSources)
    sourcePlane_indices_y = np.zeros(noOfSources)
    sourcePlane_indices_z = np.zeros(noOfSources)


    scatterAngle = np.zeros((noOfSources, noOfEvents))
    electronEnergy_eV = np.zeros((noOfSources, noOfEvents))

    radius = np.zeros((noOfSources, noOfEvents))

    axisVector = np.zeros((noOfSources, noOfEvents), dtype=list)
    sourceVector = np.zeros((noOfSources, noOfEvents), dtype=list)

    events = np.zeros((noOfSources*noOfEvents, 11))
    k = 0

    for j in range(0, noOfSources) :
        # use Current source instead of fixed source(20,25,-123)
        sourcePlane_indices_x[j] = Current_source_x  #round(random.uniform(0, 49), 0)
        sourcePlane_indices_y[j] = Current_source_y  #round(random.uniform(0, 49), 0)
        sourcePlane_indices_z[j] = Current_source_z  #round(random.uniform(-200, -100), 0)
        
        #print("source plane indices : ", sourcePlane_indices_x, sourcePlane_indices_y, sourcePlane_indices_z)

        for i in range(0,noOfEvents) :

            #.........Randon values for scattering plane and absorption plane point of interaction are generated by selecting random values for array index.
            scatterPlane_indices_x[j,i] = round(random.uniform(0, 50), 0) #np.random.randint(0, 20*size_scatterPlane)
            scatterPlane_indices_y[j,i] = round(random.uniform(0, 50), 0) #np.random.randint(0, 20*size_scatterPlane)
            scatterPlane_indices_z[j,i] = 0 # round(random.uniform(0, 10), 6)

            absorbPlane_indices_x[j,i] = round(random.uniform(0, 45), 0) #np.random.randint(-4, 44)
            absorbPlane_indices_y[j,i] = round(random.uniform(0, 45), 0) #np.random.randint(-4, 44)
            absorbPlane_indices_z[j,i] = 100 # round(random.uniform(100, 110), 6)

            axisVector[j,i] = ([scatterPlane_indices_x[j,i] - absorbPlane_indices_x[j,i], scatterPlane_indices_y[j,i] - absorbPlane_indices_y[j,i], scatterPlane_indices_z[j,i] - absorbPlane_indices_z[j,i]])
            sourceVector[j,i] = ([sourcePlane_indices_x[j] - scatterPlane_indices_x[j,i], sourcePlane_indices_y[j] - scatterPlane_indices_y[j,i], sourcePlane_indices_z[j] - scatterPlane_indices_z[j,i]])

            
            # if np.dot(axisVector[j,i],sourceVector[j,i])/ (np.linalg.norm(axisVector[j,i], ord=2) * np.linalg.norm(sourceVector[j,i], ord=2)) in range(-1,1) :
            scatterAngle[j,i] = math.acos(np.dot(axisVector[j,i],sourceVector[j,i])/ (np.linalg.norm(axisVector[j,i], ord=2) * np.linalg.norm(sourceVector[j,i], ord=2))) * 180/math.pi
            

            #..............Electron energy................

            #electronEnergy_J[i] = (initialEnergy_J * (1 - (1/(((initialEnergy_J/(eMass_J*(c**2)))*(1 - np.cos(scatterAngle[i] * math.pi / 180. ))) + 1)))) * 6.2415093432602 * (10**12)
            electronEnergy_eV[j,i] = params.initialEnergy_eV * (1 - (1/(((params.initialEnergy_eV/(params.eMass_eV))*(1 - np.cos(scatterAngle[j,i] * math.pi / 180. ))) + 1)))
            
            ###### Adding scattering angle uncertainty ..............................
            percentage_uncertainty = 0.1  # 5%

            sigma = percentage_uncertainty * scatterAngle[j,i]
            scatterAngle_un = np.random.normal(loc=scatterAngle[j,i], scale=sigma)
            # scatterAngle[j,i] = scatterAngle_un
            
            events[k,0] = sourcePlane_indices_x[j]
            events[k,1] = sourcePlane_indices_y[j]
            events[k,2] = sourcePlane_indices_z[j]
            events[k,3] = scatterPlane_indices_x[j,i]
            events[k,4] = scatterPlane_indices_y[j,i]
            events[k,5] = scatterPlane_indices_z[j,i]
            events[k,6] = absorbPlane_indices_x[j,i]
            events[k,7] = absorbPlane_indices_y[j,i]
            events[k,8] = absorbPlane_indices_z[j,i]
            events[k,9] = scatterAngle[j,i] 
            events[k,10] = electronEnergy_eV[j,i] 

            k = k+1


#....................Print intermediate values.....................

            # print('Axis vector : ', axisVector[j,i])
            # print('source vector : ', sourceVector[j,i])
            # print('dot :', np.dot(axisVector[j,i],sourceVector[j,i]))
            # print(i, "\nSource plane indices : ", sourcePlane_indices_x[j], sourcePlane_indices_y[j], sourcePlane_indices_z[j],
            #   "\nScattering plane indices : ", scatterPlane_indices_x[j,i], scatterPlane_indices_y[j,i], scatterPlane_indices_z[j,i],
            #   "\nAbsorbtion plane indices : ", absorbPlane_indices_x[j,i], absorbPlane_indices_y[j,i], absorbPlane_indices_z[j,i],
            #   "\nElectron energy : ", electronEnergy_eV[j,i],
            #   "\nScattering angle : ",scatterAngle[j,i])

    #....................Convert data to a DataFrame........................

    columns = ['source_x', 'source_y', 'source_z', 'scat_x', 'scat_y', 'scat_z', 'absorb_x', 'absorb_y', 'absorb_z', 
                'theta', 'e_energy']

    df = pd.DataFrame(events, columns=columns)

    # csv_file_name = config.data_dir + "/" + param.file_name + "" + param.ext
    OUT_DIR = DATA_DIR
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    #save using Current_source_*so each call writes one unique csv
    csv_file_name = os.path.join(OUT_DIR, "events_" + str(int(Current_source_x)) + '_' + str(int(Current_source_y)) + '_' + str(int(Current_source_z)) + ".csv")

    # csv_file_name = "/home/lasya/Lasya/Reconstruction/temp/" + "events_" + str(int(sourcePlane_indices_x[j-1])) + '_' + str(int(sourcePlane_indices_y[j-1])) + '_' +  str(int(sourcePlane_indices_x[j])) + '_' + str(int(sourcePlane_indices_y[j])) + '_' + str(int(sourcePlane_indices_z[j])) + ".csv"
    #config.data_dir
    # Save the DataFrame to a CSV file
    df.to_csv(csv_file_name, index=False)

"""#5position manually

noOfSourcePerImage = 1
noOfEventsPerSource = 10
#noOfSources = 2500


positions =[(0,0),(5,5),(10,20),(25,30),(49,49)]

for (x,y) in positions :
    Current_source_x = x
    Current_source_y = y
    Current_source_z = -123
    genSimEvents(noOfSourcePerImage, noOfEventsPerSource)
print("Generated for validation CSV files:", len(positions))"""


#for i in range(0, noOfSources) :
    #genSimEvents(noOfSourcePerImage, noOfEventsPerSource)


def main():
    global Current_source_x, Current_source_y, Current_source_z

    noOfSourcePerImage = 1
    noOfEventsPerSource = 1000

    grid_x = 50
    grid_y = 50
    count = 0

    for x in range(grid_x):
        for y in range(grid_y):
            Current_source_x = x
            Current_source_y = y
            Current_source_z = -123
            genSimEvents(noOfSourcePerImage, noOfEventsPerSource)
            count += 1

    print("Generated full dataset CSV files:", count)

#5 random source position
"""
noOfSourcePerImage = 1
noOfEventsPerSource = 10
noOfSource = 5

random_positions = []

for _ in range (noOfSource):
    x = random.randint(0,49)
    y = random.randint(0,49)
    random_positions.append((x,y))
    
for(x,y) in random_positions:
    Current_source_x = x
    Current_source_y = y
    Current_source_z = -123
    genSimEvents(noOfSourcePerImage, noOfEventsPerSource)
    
print("Generated for validation CSV files:", len(random_positions))
print(" Source position usedd:", random_positions)
"""

#.................plots.............................

    #............scattering angle vs electron energy...........................

    # current_time = time.localtime() 
    # formatted_time = time.strftime("%Y-%m-%d_%H:%M", current_time)

    # plot_loc1 = os.path.join(config.png_dir,"theta_vs_electron_energy_" + formatted_time + ".png") 
    # plt.plot(scatterAngle[0,:], electronEnergy_eV[0,:], '.', color = 'g', label = 'eV')
    # plt.xlim([0,180])
    # plt.ylim(min(electronEnergy_eV[0,:]), max(electronEnergy_eV[0,:] + 1))
    # plt.yscale("log")
    # plt.xlabel("Scattering angle(°)")
    # plt.ylabel("Electron energy")
    # plt.title("Theta_vs_electron_energy")
    # plt.legend()
    # plt.savefig(plot_loc1, bbox_inches='tight')

    # #............plot source, scatter and absorption points....................

    # plot_loc2 = os.path.join(config.png_dir,"simulated_points_" + formatted_time + ".png")
    # plt.style.use('_mpl-gallery')
    # fig, ax = plt.subplots(subplot_kw={"projection": "3d"})
    # ax.scatter(sourcePlane_indices_x, sourcePlane_indices_y, sourcePlane_indices_z, color='blue', label='source points')
    # ax.scatter(scatterPlane_indices_x, scatterPlane_indices_y, scatterPlane_indices_z, color='red', label='scatter points')
    # ax.scatter(absorbPlane_indices_x, absorbPlane_indices_y, absorbPlane_indices_z, color='green', label='absorption points')
    # plt.xlabel("x")
    # plt.ylabel("y")
    # plt.clabel("z")
    # plt.title("Simulated source, scatter and absorption points")
    # plt.savefig(plot_loc2, bbox_inches='tight')


if __name__ == "__main__":
    main()
